# Generated by Django 5.0.4 on 2024-05-21 18:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 18, 14, 29, 951517, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
