# Generated by Django 5.0.4 on 2024-05-06 13:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.DateField(default=datetime.datetime(2024, 5, 6, 13, 26, 36, 854581)),
        ),
    ]
