# Generated by Django 5.0.4 on 2024-05-21 10:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 10, 27, 53, 791783), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 21, 10, 27, 53, 791802), verbose_name='Дата изменения'),
        ),
    ]
