# Generated by Django 5.0.4 on 2024-06-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_version'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='version',
            unique_together={('product', 'code')},
        ),
    ]
